### ISSUE TITLE
Unitialized Constant NumberedList

### ISSUE THREAD

**Issue by bengarishodge** [r26D/numbered_list#1]
### Issue
Tried to run in rails project and cant find the NumberedList constant/namespace in 'item_value.rb'

### Situation
- added gem
- created NumberedList class
- `rails console`
- ERROR!

### Error
`~/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant NumberedList (NameError)`

----- Error actually happens here ------

- ` ~/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/numbered_list-0.0.3/lib/numbered_list/item_value.rb:2`

-----------------------------------------

It might be in issue on how its being required? I didn't think it would need a bilateral 'require' statement. 

### Solution

- Changed all references to "NumberedList::ItemValue" => "ItemValue"
- Changed all references to "NumberedList::MarshallBase" => "MarshallBase"
- Moved 'item_value.rb' & 'marshall_base.rb' out of 'numbered_list' dir to top
- Changed
```ruby
require 'numbered_list/item_value'

class NumberedList
  attr_reader :item
...
```
- to

```ruby
require 'item_value'
require 'marshall_base'

class NumberedList
  attr_reader :item
...
```

- replaced `require 'numbered_list/item_value'` with `require 'item_value'` and `require 'marshall_base'`

now in practice

```ruby
class Enums::PipeState < NumberedList
  item({name: "RECEIVED",
        formatted: "Received",
        order_value: 1,
        description: "Received"})
end

...
# => #<Enums::PipeState:0x00007fd7a02c46e0 @item=#<ItemValue name="RECEIVED", formatted="Received", order_value=1, description="Received">>

```

### Additional Request
Also, can you add that 'values' gem is a dependency?

**Comment by delmendo** [comment]
I fixed the problem - and changed the class a bit and added in a new unit test.
